models/InstallForm.php
<?php
/**
 * @copyright Copyright &copy; communityii, 2014
 * @package yii2-user
 * @version 1.0.0
 * @see https://github.com/communityii/yii2-user
 */

namespace communityii\user\models;

use Yii;
use yii\base\Model;
use yii\helpers\ArrayHelper;
use kartik\password\StrengthValidator;
use communityii\user\Module;

/**
 * Installation Form model for the module
 *
 * @property string $access_code
 * @property string $username
 * @property string $password
 * @property string $password_confirm
 * @property string $email
 *
 * @author Kartik Visweswaran <kartikv2@gmail.com>
 * @since 1.0
 */
class InstallForm extends Model
{
    /**
     * @var string installation access code
     */
    public $access_code;

    /**
     * @var string the superuser name
     *
     */
    public $username;

    /**
     * @var string the superuser password
     */
    public $password;

    /**
     * @var string superuser password confirmation field
     */
    public $password_confirm;

    /**
     * @var string superuser email address
     *
     */
    public $email;

    /**
     * @var string the action for the install that will derive the scenario
     */
    public $action;

    private $_module;

    /**
     * Initialize InstallForm model
     */
    public function init()
    {
        Module::validateConfig($this->_module);
        parent::init();
    }

    /**
     * InstallForm model validation rules
     *
     * @return array
     */
    public function rules()
    {
        $config = $this->_module->registrationSettings;
        $rules = [
            [['access_code', 'username', 'password', 'email', 'password_confirm', 'action'], 'safe'],
            ['access_code', 'required', 'on' => [Module::UI_ACCESS]],
            ['access_code', 'checkAccess', 'on' => [Module::UI_ACCESS]],
            [['username', 'email'], 'filter', 'filter' => 'trim', 'on' => [Module::UI_INSTALL]],
            ['email', 'email', 'on' => [Module::UI_INSTALL]],
            [['username', 'password', 'password_confirm', 'email'], 'required', 'on' => [Module::UI_INSTALL]],
            ['username', 'match', 'pattern' => $config['userNamePattern'], 'message' => $config['userNameValidMsg'], 'on' => [Module::UI_INSTALL]],
            ['username', 'string'] + $config['userNameRules'] + ['on' => Module::UI_INSTALL],
            ['password_confirm', 'compare', 'compareAttribute' => 'password', 'on' => [Module::UI_INSTALL]],
            [['password'], StrengthValidator::className()] +  $this->_module->passwordSettings['strengthRules'] + ['on' => [Module::UI_INSTALL]]
        ];
        if (in_array(Module::UI_INSTALL, $this->_module->passwordSettings['validateStrength'])) {
            $rules[] = [['password'], StrengthValidator::className()] +
                $this->_module->passwordSettings['strengthRules'] +
                ['on' => [Module::UI_INSTALL]];
        }
        return $rules;
    }

    /**
     * Checks the access_code against the `installAccessCode` in the module configuration.
     * This is the 'checkAccess' validator as declared in rules().
     */
    public function checkAccess()
    {
        if ($this->_module->installAccessCode !== $this->access_code) {
            $this->addError('access_code', Yii::t('user', 'The installation access code entered is incorrect.'));
        }
        $userComponent = Yii::$app->get('user');
        if (!$userComponent instanceof \communityii\user\components\User) {
            $this->addError('access_code', Yii::t('user', 'You have not setup a valid class for your user component in your application configuration file. ' .
                'The class must extend {classValid}. Class currently set: {classSet}.', [
                    'classValid' => '\communityii\user\components\User' ,
                    'classSet' => $userComponent::classname()
                ]
            ));
        }
    }

    /**
     * Attribute labels for the InstallForm model
     *
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'access_code' => Yii::t('user', 'Installation Access Code'),
            'username' => Yii::t('user', 'Username'),
            'password' => Yii::t('user', 'Password'),
            'password_confirm' => Yii::t('user', 'Confirm Password'),
            'email' => Yii::t('user', 'Email'),
        ];
    }

    public function attributeHints() {
        return [
            'access_code' => Yii::t('user', 'Enter the installation access code as setup in your module configuration.'),
            'username' => Yii::t('user', 'Select an username for the superuser'),
            'password' => Yii::t('user', 'Select a password for the superuser'),
            'password_confirm' => Yii::t('user', 'Reconfirm the superuser password'),
            'email' => Yii::t('user', 'Enter a valid email for the superuser'),
        ];

    }
}

controllers/InstallController.php
<?php

/**
 * @copyright Copyright &copy; communityii, 2014
 * @package yii2-user
 * @version 1.0.0
 * @see https://github.com/communityii/yii2-user
 */

namespace communityii\user\controllers;

use Yii;
use communityii\user\Module;
use communityii\user\models\User;
use communityii\user\models\InstallForm;

/**
 * Install controller for managing the install and setup of admin user for this module.
 *
 * @author Kartik Visweswaran <kartikv2@gmail.com>
 * @since 1.0
 */
class InstallController extends BaseController
{
    const UI_INIT_SETUP = 'begin_setup';
    public $layout = 'install';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        if (isset($this->module->installAccessCode) && !$this->module->hasSuperUser()) {
            $model = new InstallForm(['scenario' => Module::UI_ACCESS]);
            if (!isset($model->action)) {
                $model->action = self::UI_INIT_SETUP;
            }
            if ($model->load(Yii::$app->request->post())) {
                if ($model->action === self::UI_INIT_SETUP && $model->validate()) {
                    $model = new InstallForm(['scenario' => Module::UI_INSTALL]);
                }
                elseif ($model->action === Module::UI_ACCESS && $model->validate()) {
                    $model = new InstallForm(['scenario' => Module::UI_INSTALL]);
                    $model->scenario = Module::UI_INSTALL;
                    $model->action = Module::UI_INSTALL;
                    if (isset(Yii::$app->params['adminEmail'])) {
                        $model->email = Yii::$app->params['adminEmail'];
                    }
                }
                elseif ($model->action === Module::UI_INSTALL) {
                    $model->access_code = $this->module->installAccessCode;
                    if ($model->validate()) {
                        $createUser = User::create([
                            'username' => $model->username,
                            'password_raw' => $model->password,
                            'email' => $model->email,
                            'status' => User::STATUS_SUPERUSER
                        ], Module::UI_INSTALL);
                        $user = $createUser['model'];
                        if (!$createUser['status']) {
                            Yii::$app->session->setFlash('error', Yii::t('user', 'Error creating the superuser. Fix the following errors:') . '<br/><br/>' .
                                Module::showErrors($user)
                            );
                            $model->action = Module::UI_INSTALL;
                            $model->scenario = Module::UI_INSTALL;
                        }
                        else {
                            Yii::$app->session->setFlash('success', Yii::t('user',
                                'The user module has been successfully installed. You have been automatically logged in as the superuser (username: {username}).',
                                ['username' => "<strong>'" . $model->username . "'</strong>"]));
                            Yii::$app->session->setFlash('warning', Yii::t('user', 'It is recommended to remove the install access code from your module configuration for better performance and security.'));
                            Yii::$app->user->login($user);
                            return $this->forward(Module::ACTION_ADMIN_VIEW, ['id'=>$user->id]);
                        }
                    }
                    else {
                        $model->action = Module::UI_ACCESS;
                        $model->scenario = Module::UI_ACCESS;
                    }
                }
            }
            return $this->render($model->scenario, ['model' => $model, 'user' => isset($user) ? $user : null]);
        }
        return $this->safeRedirect();
    }
}

views/install/access.php
<?php

use communityii\user\Module;
use kartik\helpers\Html;
use kartik\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var communityii\user\models\InstallForm $model
 * @var kartik\widgets\ActiveForm $form
 */
$model->action = Module::UI_ACCESS;
$hints = $model->attributeHints();
?>
<p class="text-info text-center"><?= Yii::t('user', 'Welcome! You are 2 steps away to start using the yii2-user module.') ?></p>
<?php $form = ActiveForm::begin(); ?>
<div class="y2u-box">
    <div class = "y2u-padding">
        <div class="page-header">
            <h3><?= Yii::t('user', 'Getting Started') ?>
                <small><?= Yii::t('user', 'Step 1 of 2') ?></small>
            </h3>
        </div>
        <?= $form->field($model, 'access_code')->passwordInput()->hint($hints['access_code']) ?>
        <?= Html::activeHiddenInput($model, 'action') ?>
    </div>
    <div class="y2u-box-footer">
        <?= Html::a('<i class="glyphicon glyphicon-question-sign"></i> ' . Yii::t('user', 'Help'), '#help', [
            'class' => 'btn btn-info pull-left', 'onclick' => '$("#help").slideToggle("slow");'
        ]) ?>
        <?= Html::submitButton(Yii::t('user', 'Proceed') . ' &raquo;', ['class' => 'btn btn-success']) ?>
    </div>
</div>
<?php ActiveForm::end(); ?>
<br>
<div id="help" class="alert alert-info" style="display:none;">
    <h4><i class="glyphicon glyphicon-exclamation-sign"></i> Important</h4>
    <small>
    <ul style="padding-left: 15px">
        <li>You must have setup a module named <code>user</code> and setup an install access code for the module in your configuration file.</li>
        <li>You must have setup the user component in your configuration file to use/extend <code>communityii\user\components\User</code> class.</li>
        <li>You must have run the database migrations as mentioned in documentation.</li>
        <li>You should optionally edit the user module settings for your user and password preferences.</li>
        <li>The installer would guide you to create a superuser. Ensure you remember the superuser access credentials for future.</li>
    </ul>
    </small>
</div>

views/install/install.php
<?php

use communityii\user\Module;
use kartik\helpers\Html;
use kartik\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var communityii\user\models\InstallForm $model
 * @var kartik\widgets\ActiveForm $form
 */
$model->action = Module::UI_INSTALL;
?>
<p class="text-success text-center"><?= Yii::t('user', 'Access code validated! Setup a superuser to finish the install.') ?></p>
<?php $form = ActiveForm::begin(); ?>
<div class="y2u-box">
    <div class = "y2u-padding">
        <div class="page-header">
            <h3><?= Yii::t('user', 'Setup Superuser') ?>
                <small><?= Yii::t('user', 'Step 2 of 2') ?></small>
            </h3>
        </div>
        <?= $form->field($model, 'username') ?>
        <?php
        if ($this->context->module->passwordSettings['strengthMeter']) {
            echo $form->field($model, 'password')->widget('\kartik\password\PasswordInput');
        }
        else {
            echo $form->field($model, 'password')->passwordInput();
        }
        ?>
        <?= $form->field($model, 'password_confirm')->passwordInput() ?>
        <?= $form->field($model, 'email') ?>
        <?= Html::activeHiddenInput($model, 'action') ?>
    </div>
    <div class="y2u-box-footer">
        <?= Html::a('&laquo; ' . Yii::t('user', 'Back'), ['install/index'], ['class' => 'btn btn-danger pull-left']) ?>
        <?= Html::resetButton('<i class="glyphicon glyphicon-remove"></i> ' . Yii::t('user', 'Reset'), ['class' => 'btn btn-default']) ?>
        <?= Html::submitButton('<i class="glyphicon glyphicon-ok"></i> ' . Yii::t('user', 'Finish'), ['class' => 'btn btn-success']) ?>
    </div>
</div>
<?php ActiveForm::end(); ?>